/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.4 */
/* Fri May 27 09:17:06 2022 */

/* parameterized module instance */
romBCD __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
